name: Build and Deploy TypeScript to GitHub Pages

on:
  push:
    branches:
      - master  # Runs whenever you push to master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Compile TypeScript
        run: npx tsc

      - name: Commit Compiled JavaScript
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add src/scripts/compiledJS
          git commit -m "Auto-compiled TypeScript to JavaScript" || echo "No changes to commit"
          git push origin master
